---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: community-minecraft
  namespace: community-minecraft
spec:
  template:
    spec:
      nodeSelector:
        location: gcp
      $setElementOrder/containers:
      - name: community-minecraft
      containers:
      - name: community-minecraft
        image: devlaunchers/community-minecraft:sha-807db27
        $setElementOrder/env:
        - name: DISABLE_BACKUP
        env:
        - name: DISABLE_BACKUP
          value: "true"
        resources:
          limits:
            cpu: 1500m
            memory: 3172Mi
          requests:
            cpu: 1000m
            memory: 2048Mi