---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: community-minecraft
  namespace: community-minecraft
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: community-minecraft
      containers:
      - image: devlaunchers/community-minecraft:sha-f59375b
        name: community-minecraft
