listeners:
- query_port: 25577
  motd: '&r&c&k!!!&e DevLaunchers - Hub - MC 1.16.4 &c&k !!'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - server1
  bind_local_address: false
  host: minecraft.devlaunchers.com:31672
  max_players: 20
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: -1
stats: 046a85b2-1185-44fb-9087-bdd8afe7c0e1
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: true
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  server1:
    motd: '&r&c&k!!!&e DevLaunchers - Survival  - MC 1.16.4 &c&k !!'
    address: localhost:25566
    restricted: false
