apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: community-minecraft
  name: community-minecraft
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: community-minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-minecraft
  template:
    metadata:
      labels:
        app: community-minecraft
    spec:
      containers:
      - name: community-minecraft
        image: ubuntu
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 80
          protocol: UDP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8080
          protocol: UDP
        resources:
          limits:
            cpu: 1000m
            memory: 3072Mi
          requests:
            cpu: 500m
            memory: 2048Mi
