apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: community-minecraft
  name: community-minecraft
  labels:
    app: community-minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-minecraft
  template:
    metadata:
      labels:
        app: community-minecraft
    spec:
      containers:
      - name: community-minecraft
        image: devlaunchers/community-minecraft
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 25565
          protocol: TCP
        - containerPort: 25565
          protocol: UDP
        - containerPort: 22
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 3072Mi
          requests:
            cpu: 500m
            memory: 2048Mi
