apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: community-minecraft
  name: community-minecraft-waterfall
  labels:
    app: community-minecraft-waterfall-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-minecraft-waterfall-app
  template:
    metadata:
      labels:
        app: community-minecraft-waterfall-app
    spec:
      containers:
      - name: community-minecraft-waterfall
        image: devlaunchers/community-minecraft:sha-a515498
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 25565
          protocol: TCP
        - containerPort: 25565
          protocol: UDP
        - containerPort: 22
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
        volumeMounts:
        - name: ssh-config
          mountPath: "/root/.ssh"
      volumes:
      - name: ssh-config
        secret:
          defaultMode: 0400
          secretName: ssh-config
          items:
          - key: authorized_keys
            path: authorized_keys
