name: publish
on:
  push:
    branches:
      - main
    # Build image whenever build.txt or a file under minecraft_home or is changed
    paths:
      - 'build.txt'
      - 'minecraft_home'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devlaunchers/community-minecraft
          tag_with_ref: true
          tag_with_sha: true