on: [pull_request]
name: test
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: kubeval
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            kustomize build staging | kubeval --strict --ignore-missing-schemas
            kustomize build production | kubeval --strict --ignore-missing-schemas
      - name: conftest
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            kustomize build staging | conftest test -p .github/policy -
            kustomize build production | conftest test -p .github/policy -
